<div class="card" id="app" xmlns:v-on="http://www.w3.org/1999/xhtml">
    <div class="body">
        <form id="sign_in" action="/submit-login" method="post">
            <div class="msg">Sign in to start your session</div>
            <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">person</i>
                        </span>
                <div class="form-line">
                    <input v-model="user.email" type="text" class="form-control" name="email" placeholder="Email" required autofocus>
                </div>
            </div>
            <div class="input-group">
                        <span class="input-group-addon">
                            <i class="material-icons">lock</i>
                        </span>
                <div class="form-line">
                    <input v-model="user.password" type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-4">
                    <button v-on:click="submit()" class="btn btn-block bg-pink waves-effect">SIGN IN</button>
                </div>
            </div>
            <div class="row m-t-15 m-b--20">
                <div class="col-xs-6">
                    <a href="/register">Register Now!</a>
                </div>

            </div>
        </form>
    </div>
</div>

<?= $this->inlineScript()
    ->appendFile($this->basePath('pages/sign-in.js'))
?>