<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Chatting Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('plugins/animate-css/animate.css'))
        ->prependStylesheet($this->basePath('plugins/node-waves/waves.css'))
        ->prependStylesheet($this->basePath('css/themes/theme-deep-orange.min.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('pages/sign-in.js'))
        ->prependFile($this->basePath('js/admin.js'))
        ->prependFile($this->basePath('plugins/node-waves/waves.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
    ?>
</head>

<body class="login-page">
<div class="login-box">
    <div class="logo">
        <a href="javascript:void(0);">Chat<b>Tool</b></a>
        <small>by ZF2</small>
    </div>
    <?= $this->content ?>

</div>

</body>

</html>