<div >
    <div class="jumbotron">
        <h1>Welcome to <span class="zf-green">Chattool by ZF2</span></h1>
        <p><a class="btn btn-success btn-lg" href="javascript:void(0)" @click="openChatbox()" >Call our supporter &raquo;</a></p>
    </div>
    <div id="chatbox">
        <div class="chat_window">
            <div class="top_menu" >
                <div class="buttons">
                    <div class="button close" @click="closeChatbox()"></div>
<!--                    <div class="button minimize"></div>-->
                    <div class="button maximize" @click="openChatbox()"></div>
                </div>
                <div class="title">{{ current_chatting_user }}</div>
            </div>
            <div v-if="!isClosed">
                <ul id="messages_list" class="messages" v-chat-scroll>
                    <div v-for="message in messages" >
                        <li class="message left appeared" v-if="message.sender_id != user.id" >
                            <div class="avatar"></div>
                            <div class="text_wrapper">
                                <div class="text">{{ message.content }}</div>
                            </div>
                        </li>
                        <li class="message right appeared" v-else>
                            <div class="avatar"></div>
                            <div class="text_wrapper">
                                <div class="text">{{ message.content }}</div>
                            </div>
                        </li>
                    </div>
                </ul>
                <div class="bottom_wrapper clearfix">
                    <div class="message_input_wrapper">
                        <input v-on:keyup.13="sendMessage()" class="message_input" v-model="text" placeholder="Type your message here..."/></div>
                    <div class="send_message" @click="sendMessage()" >
                        <div class="icon"></div>
                        <div class="text">Send</div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
